In [37]:
# Add Matplotlib inline magic command
%matplotlib inline
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import matplotlib as plt

In [38]:
# Load the permit file
data = "Resources/Annual_permits_zip_code.csv"

# Read the data file
permit_df = pd.read_csv(data)

# Display the DataFrame
permit_df

,Year,78617,78652,78653,78660,78701,78702,78703,78704,78705,...,78750,78751,78752,78753,78754,78756,78757,78758,78759,Grand Total
0,2009,208,65.0,2.0,69,354,536,583,742,270,...,313,243,151,225,229,142,421,298,447,10907
1,2010,122,37.0,1.0,46,444,543,624,852,253,...,360,322,188,331,210,211,510,387,567,11772
2,2011,86,37.0,1.0,40,430,542,653,977,277,...,346,298,134,284,236,271,530,357,631,12169
3,2012,212,NaN,1.0,31,559,631,716,1103,333,...,327,284,199,414,281,275,565,548,807,13741
4,2013,284,1.0,5.0,137,653,650,632,1096,327,...,349,313,172,512,327,256,652,443,697,15002
5,2014,210,73.0,NaN,53,683,736,631,1152,274,...,256,297,232,590,398,238,751,515,646,15063
6,2015,261,29.0,2.0,122,596,960,676,1237,284,...,286,289,288,524,292,230,715,513,659,15836
7,2016,278,130.0,107.0,310,615,904,581,1284,286,...,275,262,213,488,305,207,676,567,632,15839
8,2017,103,154.0,95.0,382,522,862,583,1044,305,...,281,253,229,505,402,208,556,478,580,15716
9,2018,200,136.0,220.0,538,670,817,577,1105,218,...,276,279,210,462,432,196,579,489,562,15906
10,2019,246,67.0,322.0,471,766,985,633,1243,358,...,337,309,249,482,484,255,657,518,620,17385
11,2020,226,127.0,158.0,441,498,634,523,981,257,...,223,225,264,340,324,202,550,467,396,14371
12,2021,173,173.0,206.0,333,314,391,340,677,111,...,194,112,144,187,233,142,373,284,344,9656
13,Grand Total,2958,1029.0,1127.0,3091,7901,10165,8739,15116,4192,...,4136,4041,2937,5908,4729,3202,8275,6457,8226,203628

In [39]:
# Check for null values
permit_df.isnull().sum()

Year           0
78617          0
78652          1
78653          1
78660          0
78701          0
78702          0
78703          0
78704          0
78705          0
78717          0
78721          0
78722          0
78723          0
78724          0
78726          0
78727          0
78729          0
78730          0
78731          0
78735          0
78736          0
78739          0
78741          0
78744          0
78745          0
78746          0
78747          0
78748          0
78749          0
78750          0
78751          0
78752          0
78753          0
78754          0
78756          0
78757          0
78758          0
78759          0
Grand Total    0
dtype: int64

In [17]:
# replacing null values with zero
permit_df['78652'].fillna(0, inplace=True)
permit_df['78653'].fillna(0, inplace=True)

In [18]:
permit_df

,Year,78617,78652,78653,78660,78701,78702,78703,78704,78705,...,78750,78751,78752,78753,78754,78756,78757,78758,78759,Grand Total
0,2009,208,65.0,2.0,69,354,536,583,742,270,...,313,243,151,225,229,142,421,298,447,10907
1,2010,122,37.0,1.0,46,444,543,624,852,253,...,360,322,188,331,210,211,510,387,567,11772
2,2011,86,37.0,1.0,40,430,542,653,977,277,...,346,298,134,284,236,271,530,357,631,12169
3,2012,212,0.0,1.0,31,559,631,716,1103,333,...,327,284,199,414,281,275,565,548,807,13741
4,2013,284,1.0,5.0,137,653,650,632,1096,327,...,349,313,172,512,327,256,652,443,697,15002
5,2014,210,73.0,0.0,53,683,736,631,1152,274,...,256,297,232,590,398,238,751,515,646,15063
6,2015,261,29.0,2.0,122,596,960,676,1237,284,...,286,289,288,524,292,230,715,513,659,15836
7,2016,278,130.0,107.0,310,615,904,581,1284,286,...,275,262,213,488,305,207,676,567,632,15839
8,2017,103,154.0,95.0,382,522,862,583,1044,305,...,281,253,229,505,402,208,556,478,580,15716
9,2018,200,136.0,220.0,538,670,817,577,1105,218,...,276,279,210,462,432,196,579,489,562,15906
10,2019,246,67.0,322.0,471,766,985,633,1243,358,...,337,309,249,482,484,255,657,518,620,17385
11,2020,226,127.0,158.0,441,498,634,523,981,257,...,223,225,264,340,324,202,550,467,396,14371
12,2021,173,173.0,206.0,333,314,391,340,677,111,...,194,112,144,187,233,142,373,284,344,9656
13,Grand Total,2958,1029.0,1127.0,3091,7901,10165,8739,15116,4192,...,4136,4041,2937,5908,4729,3202,8275,6457,8226,203628

In [23]:
# Drop last row 
permit_df = permit_df[:-1]

In [24]:
permit_df

,Year,78617,78652,78653,78660,78701,78702,78703,78704,78705,...,78750,78751,78752,78753,78754,78756,78757,78758,78759,Grand Total
0,2009,208,65.0,2.0,69,354,536,583,742,270,...,313,243,151,225,229,142,421,298,447,10907
1,2010,122,37.0,1.0,46,444,543,624,852,253,...,360,322,188,331,210,211,510,387,567,11772
2,2011,86,37.0,1.0,40,430,542,653,977,277,...,346,298,134,284,236,271,530,357,631,12169
3,2012,212,0.0,1.0,31,559,631,716,1103,333,...,327,284,199,414,281,275,565,548,807,13741
4,2013,284,1.0,5.0,137,653,650,632,1096,327,...,349,313,172,512,327,256,652,443,697,15002
5,2014,210,73.0,0.0,53,683,736,631,1152,274,...,256,297,232,590,398,238,751,515,646,15063
6,2015,261,29.0,2.0,122,596,960,676,1237,284,...,286,289,288,524,292,230,715,513,659,15836
7,2016,278,130.0,107.0,310,615,904,581,1284,286,...,275,262,213,488,305,207,676,567,632,15839
8,2017,103,154.0,95.0,382,522,862,583,1044,305,...,281,253,229,505,402,208,556,478,580,15716
9,2018,200,136.0,220.0,538,670,817,577,1105,218,...,276,279,210,462,432,196,579,489,562,15906
10,2019,246,67.0,322.0,471,766,985,633,1243,358,...,337,309,249,482,484,255,657,518,620,17385
11,2020,226,127.0,158.0,441,498,634,523,981,257,...,223,225,264,340,324,202,550,467,396,14371

In [26]:
# Drop last column
permit_df = permit_df.iloc[:, :-1]

In [34]:
permit_df

,Year,78617,78652,78653,78660,78701,78702,78703,78704,78705,...,78749,78750,78751,78752,78753,78754,78756,78757,78758,78759
0,2009,208,65.0,2.0,69,354,536,583,742,270,...,173,313,243,151,225,229,142,421,298,447
1,2010,122,37.0,1.0,46,444,543,624,852,253,...,256,360,322,188,331,210,211,510,387,567
2,2011,86,37.0,1.0,40,430,542,653,977,277,...,350,346,298,134,284,236,271,530,357,631
3,2012,212,0.0,1.0,31,559,631,716,1103,333,...,242,327,284,199,414,281,275,565,548,807
4,2013,284,1.0,5.0,137,653,650,632,1096,327,...,319,349,313,172,512,327,256,652,443,697
5,2014,210,73.0,0.0,53,683,736,631,1152,274,...,313,256,297,232,590,398,238,751,515,646
6,2015,261,29.0,2.0,122,596,960,676,1237,284,...,342,286,289,288,524,292,230,715,513,659
7,2016,278,130.0,107.0,310,615,904,581,1284,286,...,335,275,262,213,488,305,207,676,567,632
8,2017,103,154.0,95.0,382,522,862,583,1044,305,...,365,281,253,229,505,402,208,556,478,580
9,2018,200,136.0,220.0,538,670,817,577,1105,218,...,352,276,279,210,462,432,196,579,489,562
10,2019,246,67.0,322.0,471,766,985,633,1243,358,...,336,337,309,249,482,484,255,657,518,620
11,2020,226,127.0,158.0,441,498,634,523,981,257,...,280,223,225,264,340,324,202,550,467,396

In [35]:
permits_issued =

         0     1     2     3     4     5     6     7     8     9     10    11
Year   2009  2010  2011  2012  2013  2014  2015  2016  2017  2018  2019  2020
78617   208   122    86   212   284   210   261   278   103   200   246   226
78652    65    37    37     0     1    73    29   130   154   136    67   127
78653     2     1     1     1     5     0     2   107    95   220   322   158
78660    69    46    40    31   137    53   122   310   382   538   471   441
78701   354   444   430   559   653   683   596   615   522   670   766   498
78702   536   543   542   631   650   736   960   904   862   817   985   634
78703   583   624   653   716   632   631   676   581   583   577   633   523
78704   742   852   977  1103  1096  1152  1237  1284  1044  1105  1243   981
78705   270   253   277   333   327   274   284   286   305   218   358   257
78717   210   171   134   269   431   375   396   430   527   424   450   332
78721   118   138   163   173   169   222   231   247   413   372   335   316
78722   131   126   120   162   160   144   157   139   165   129   151   121
78723   415   352   420   452   580   616   781   695   741   712   677   713
78724   161   107   141   116   165   260   228   204   311   287   499   553
78726    69   119   173   145   172   160   144   117   100   113   118   109
78727   535   290   224   224   276   263   353   337   261   338   291   267
78729   115    65   137   140   131   115   174   119   176   161   121   116
78730   113   155   188   193   213   185   188   165   166   193   145   149
78731   538   521   698   635   714   611   585   533   561   609   718   560
78735   137   192   214   208   193   202   211   154   242   267   185   176
78736    44    44    60    48    57    79    95    75   157   100   137    50
78739   207   217   240   244   244   303   316   227   220   181   169   205
78741   287   339   344   429   590   507   446   478   565   516   452   370
78744   290   286   283   376   655   500   747   946   701   655   915   989
78745   590   798   715   751   664   827  1049   945   754   829   970   756
78746   434   603   539   411   413   408   414   478   461   452   447   345
78747   246   202   176   259   386   352   204   260   420   405   526   590
78748   570   551   508   735   616   554   490   534   632   601   496   336
78749   173   256   350   242   319   313   342   335   365   352   336   280
78750   313   360   346   327   349   256   286   275   281   276   337   223
78751   243   322   298   284   313   297   289   262   253   279   309   225
78752   151   188   134   199   172   232   288   213   229   210   249   264
78753   225   331   284   414   512   590   524   488   505   462   482   340
78754   229   210   236   281   327   398   292   305   402   432   484   324
78756   142   211   271   275   256   238   230   207   208   196   255   202
78757   421   510   530   565   652   751   715   676   556   579   657   550
78758   298   387   357   548   443   515   513   567   478   489   518   467
78759   447   567   631   807   697   646   659   632   580   562   620   396

In [40]:
permit_df.describe()

,78617,78652,78653,78660,78701,78702,78703,78704,78705,78717,...,78750,78751,78752,78753,78754,78756,78757,78758,78759,Grand Total
count,14.000000,13.000000,13.000000,14.000000,14.000000,14.000000,14.000000,14.0000,14.000000,14.000000,...,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000
mean,397.642857,158.307692,172.846154,433.142857,1071.785714,1382.571429,1177.928571,2043.5000,553.214286,658.857143,...,568.500000,537.642857,400.714286,803.714286,634.428571,431.071429,1129.285714,880.071429,1129.571429,27642.214286
std,739.483459,267.057542,305.741952,786.045688,1969.860760,2534.058002,2178.001712,3766.8842,1048.966024,1221.174961,...,1027.949696,1009.717372,731.403228,1474.074282,1181.427280,798.587259,2059.388349,1607.593063,2046.072550,50700.568192
min,86.000000,1.000000,1.000000,31.000000,314.000000,391.000000,340.000000,677.0000,111.000000,134.000000,...,194.000000,112.000000,134.000000,187.000000,210.000000,142.000000,373.000000,284.000000,344.000000,9656.000000
25%,179.750000,37.000000,2.000000,57.000000,457.500000,565.000000,581.500000,978.0000,260.250000,224.750000,...,275.250000,255.250000,176.000000,333.250000,247.250000,203.250000,535.000000,401.000000,563.250000,12562.000000
50%,211.000000,73.000000,95.000000,223.500000,577.500000,693.000000,627.500000,1099.5000,280.500000,385.500000,...,299.500000,286.500000,211.500000,472.000000,314.500000,220.500000,572.000000,483.500000,625.500000,15032.500000
75%,257.250000,136.000000,206.000000,426.250000,665.750000,893.500000,648.000000,1215.7500,321.500000,430.750000,...,343.750000,306.250000,244.750000,510.250000,401.000000,255.750000,671.250000,517.250000,655.750000,15838.250000
max,2958.000000,1029.000000,1127.000000,3091.000000,7901.000000,10165.000000,8739.000000,15116.0000,4192.000000,4881.000000,...,4136.000000,4041.000000,2937.000000,5908.000000,4729.000000,3202.000000,8275.000000,6457.000000,8226.000000,203628.000000

In [42]:
data = 'Resources/Issued_Construction_Permits.csv'
df = pd.read_csv(data)
df

C:\Users\jlemu\AppData\Roaming\Python\Python37\site-packages\IPython\core\interactiveshell.py:3166: DtypeWarning: Columns (53,54,56,58,59,60,61,62,63,64,65) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Permit Type,Permit Type Desc,Permit Num,Permit Class Mapped,Permit Class,Work Class,Condominium,Project Name,Description,TCAD ID,...,Contractor Zip,Applicant Full Name,Applicant Organization,Applicant Phone,Applicant Address 1,Applicant Address 2,Applicant City,Applicant Zip,Certificate Of Occupancy,Total Lot SQFT
0,EP,Electrical Permit,1998-002932 EP,Residential,Residential,Remodel,No,8600 Navidad Drive C 00000,New Res Elec Srv Only Eud,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN
1,BP,Building Permit,1984-004266 BP,Residential,Residential,Remodel,No,7609 Nez Perce Trace M 00000,Res,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN
2,BP,Building Permit,2002-012198 BP,Commercial,Commercial,Remodel,No,15243 Calaveras Dr,Comm Instl 3Hoods Only,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN
3,DS,Driveway / Sidewalks,2007-104828 DS,Residential,Res. Driveway & Sidewalk,NaN,NaN,NaN,XXXXX,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DS,Driveway / Sidewalks,2007-113764 DS,Residential,Res. Driveway & Sidewalk,New,NaN,12529 LA PAZ LN,SMART HOUSING,0330401147,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2064761,BP,Building Permit,2021-106810 BP,Commercial,C-1000 Commercial Remodel,Remodel,No,1030 NORWOOD PARK BLVD,Interior remodel to existing retailgrocery Wal...,0233180411,...,78232,Matt Srp,Better Built Enterprises Inc,2104925437,NaN,1123 West Blanco,San Antonio,78232,No,NaN
2064762,PP,Plumbing Permit,2021-110001 PP,Commercial,C-1000 Commercial Remodel,Remodel,No,4616 TRIANGLE AVE UNIT 200,ePlan Expedited Review Interior Remodel to an...,0224040501,...,78725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN
2064763,BP,Building Permit,2021-109085 BP,Residential,R- 434 Addition & Alterations,Addition and Remodel,No,124 BIRNAM WOOD CT,Partial demo Subterranean bridgeNotary confirmed,0113110531,...,78745,William Totten,CG&S Construction,5124441580,NaN,402 Corral,Austin,78745,Yes,54537.0
2064764,EP,Electrical Permit,2021-108593 EP,Residential,Residential,Repair,No,2103 TORO CANYON RD,Service for SFR AUSTIN 2 MILE ETJ,0123130901,...,78753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN
2064765,PP,Plumbing Permit,2021-109683 PP,Residential,Residential,Irrigation,NaN,3003 SALVIDAR BND,Installation of New Irrigation,0278201401,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN